import {
  Truck,
  Clock,
  ShieldCheck,
  BadgeCheck,
  Package,
  Calculator,
  FileText,
  Bot,
  MapPin,
  Phone,
  CreditCard,
  Hammer,
  Boxes,
  Scale,
  Wallet,
  Headphones,
  RefreshCw,
  Star,
  CheckCircle2,
  HardHat,
  Ruler,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  truck: Truck,
  clock: Clock,
  shield: ShieldCheck,
  badge: BadgeCheck,
  package: Package,
  calculator: Calculator,
  file: FileText,
  bot: Bot,
  map: MapPin,
  phone: Phone,
  card: CreditCard,
  hammer: Hammer,
  boxes: Boxes,
  scale: Scale,
  wallet: Wallet,
  headphones: Headphones,
  refresh: RefreshCw,
  star: Star,
  check: CheckCircle2,
  hardhat: HardHat,
  ruler: Ruler,
  zap: Zap,
};

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name.toLowerCase()] ?? Package;
}
