/**
 * STRIKER.Engine — 15 мощных предтем (pre-themes) для быстрого старта.
 * Каждая — полноценный чертёж: токены, каркас и контент.
 * Админ выбирает предтему и дорабатывает её вручную или через AI Studio.
 */
import type { ThemeConfigBlueprint, ThemeTokens, LayoutComponent, ContentOverrides } from "@/types/striker-engine";
import { MATERIAL_PRESETS, DEFAULT_LAYOUT, DEFAULT_COMPONENTS } from "@/types/striker-engine";

interface PresetSpec {
  id: string;
  name: string;
  description: string;
  tags: string[];
  tokens: Partial<ThemeTokens> & Pick<ThemeTokens, "palette">;
  layout?: Partial<LayoutComponent>[];
  content?: Partial<ContentOverrides>;
}

const BASE_CONTENT: ContentOverrides = {
  phone: "+7 495 123-45-67",
  address: "Москва, Каширское ш., 61",
  heroTitleMetal: "Сталь по ГОСТ",
  heroSubtitleMetal: "Арматура, швеллер, труба, лист — от 1 метра, резка в размер, доставка манипулятором.",
  heroTitleSand: "Песок и щебень",
  heroSubtitleSand: "Мытый, намывной, карьерный. Щебень 5-20, 20-40. Самосвалы 5–20 м³, отгрузка 24/7.",
  promoTag: "Акция",
  promoTitle: "Арматура А500С от 42 000 ₽/т",
  promoSubtitle: "Скидка 8% при заказе от 5 тонн",
  catalogTitle: "Прайс-лист · ГОСТ",
  trendingQueries: ["Арматура А500С", "Песок мытый", "Швеллер", "Щебень 5-20", "Труба профильная"],
};

/** Собрать чертёж из спецификации */
function buildPreset(spec: PresetSpec): ThemeConfigBlueprint {
  const now = new Date().toISOString();
  const tokens: ThemeTokens = {
    radius: 0,
    borderWeight: 2,
    noise: 0.05,
    material: "anthracite",
    viewMode: "table",
    heroMode: "split",
    searchMode: "compact",
    calculatorTabs: { metal: true, sand: true },
    ...spec.tokens,
  };

  const layout: LayoutComponent[] = spec.layout
    ? spec.layout.map((patch) => {
        const base = DEFAULT_LAYOUT.find((c) => c.id === patch.id) ?? { id: patch.id!, enabled: true };
        return { ...base, ...patch } as LayoutComponent;
      })
    : structuredClone(DEFAULT_LAYOUT);

  return {
    id: "",
    slug: `striker:${spec.id}`,
    name: spec.name,
    tokens,
    layout,
    content: { ...BASE_CONTENT, ...spec.content },
    components: structuredClone(DEFAULT_COMPONENTS),
    createdAt: now,
    updatedAt: now,
  };
}

export const STRIKER_PRESETS: ThemeConfigBlueprint[] = [
  buildPreset({
    id: "city-brutal",
    name: "Сити! Брутал",
    description: "Индустриальный металл-депо: нулевой радиус, толстый каркас, оранжевый акцент",
    tags: ["брутализм", "B2B", "таблица"],
    tokens: {
      radius: 0,
      borderWeight: 3,
      noise: 0.08,
      material: "anthracite",
      palette: { ...MATERIAL_PRESETS.anthracite, primary: "#FF3B1F" },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      phone: "+7 495 777-03-03",
      address: "Москва, Каширское ш., 61к2",
      catalogTitle: "Прайс-лист · ГОСТ 34028",
      trendingQueries: ["Арматура А500С", "Швеллер 10П", "Труба 40×20", "Лист 3мм"],
    },
  }),
  buildPreset({
    id: "vi-market",
    name: "ВИ Маркетплейс",
    description: "Современный e-commerce: светлый фон, красный акцент, сетка карточек, слайдер промо",
    tags: ["маркетплейс", "B2C", "сетка"],
    tokens: {
      radius: 12,
      borderWeight: 1,
      noise: 0.02,
      material: "chrome",
      palette: {
        background: "#F7F7F7",
        foreground: "#1A1A1A",
        card: "#FFFFFF",
        primary: "#E4002B",
        secondary: "#F0F0F0",
        muted: "#F0F0F0",
        mutedForeground: "#8A8A8A",
        border: "#E5E5E5",
      },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "8 (495) 000-00-00",
      address: "Москва, ул. Складочная, 1с18",
      promoTag: "Хит",
      promoTitle: "Арматура А500С — скидка 7%",
      promoSubtitle: "При заказе от 5 тонн с доставкой в день обращения",
      catalogTitle: "Хиты продаж",
      trendingQueries: ["Арматура", "Песок", "Щебень", "Цемент", "Швеллер"],
    },
  }),
  buildPreset({
    id: "steel-minimal",
    name: "Стальной минимализм",
    description: "Чистый светлый стиль: сталь, синий акцент, тонкие линии, строгая таблица",
    tags: ["минимализм", "B2B", "таблица"],
    tokens: {
      radius: 4,
      borderWeight: 1,
      noise: 0.02,
      material: "chrome",
      palette: {
        background: "#F4F6F8",
        foreground: "#101828",
        card: "#FFFFFF",
        primary: "#1E3A5F",
        secondary: "#E4E9EE",
        muted: "#E4E9EE",
        mutedForeground: "#667085",
        border: "#D0D5DD",
      },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      catalogTitle: "Каталог металлопроката",
      trendingQueries: ["Арматура", "Швеллер", "Уголок", "Труба", "Лист"],
    },
  }),
  buildPreset({
    id: "desert-quarry",
    name: "Песочный карьер",
    description: "Тёплая песочная палитра, терракотовый акцент, мягкие формы",
    tags: ["песок", "тёплый", "сетка"],
    tokens: {
      radius: 8,
      borderWeight: 2,
      noise: 0.06,
      material: "desert",
      palette: { ...MATERIAL_PRESETS.desert, primary: "#C2410C" },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 555-40-40",
      address: "Москва, Дорожная ул., 3",
      promoTag: "Карьер",
      promoTitle: "Песок мытый — 1 150 ₽/м³",
      promoSubtitle: "Доставка самосвалом в день заказа по Москве и Балашихе",
      catalogTitle: "Сыпучие материалы",
      trendingQueries: ["Песок мытый", "Песок карьерный", "Щебень 5-20", "Отсев", "Керамзит"],
    },
  }),
  buildPreset({
    id: "neon-tech",
    name: "Хай-тек неон",
    description: "Тёмный технологичный стиль с неоново-зелёным акцентом",
    tags: ["техно", "неон", "таблица"],
    tokens: {
      radius: 4,
      borderWeight: 1,
      noise: 0.04,
      material: "anthracite",
      palette: {
        background: "#0A120C",
        foreground: "#F0F6F2",
        card: "#101B13",
        primary: "#22E06A",
        secondary: "#16241B",
        muted: "#16241B",
        mutedForeground: "#7BA88C",
        border: "#1F3326",
      },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      catalogTitle: "Прайс · онлайн",
      trendingQueries: ["Арматура", "Труба", "Песок", "Щебень"],
    },
  }),
  buildPreset({
    id: "premium-dark",
    name: "Премиум тёмный",
    description: "Глубокий тёмный сланец с золотым акцентом, элегантная сетка",
    tags: ["премиум", "золото", "сетка"],
    tokens: {
      radius: 10,
      borderWeight: 1,
      noise: 0.03,
      material: "anthracite",
      palette: {
        background: "#121A26",
        foreground: "#F5F7FA",
        card: "#1A2433",
        primary: "#D4AF37",
        secondary: "#223044",
        muted: "#223044",
        mutedForeground: "#8FA3BF",
        border: "#2C3B52",
      },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 222-88-88",
      address: "Москва, Пресненская наб., 12",
      promoTag: "Премиум",
      promoTitle: "Металл с сертификатами ГОСТ",
      promoSubtitle: "Индивидуальные условия для строительных компаний",
      catalogTitle: "Коллекция металлопроката",
      trendingQueries: ["Арматура А500С", "Балка двутавр", "Труба профильная", "Лист"],
    },
  }),
  buildPreset({
    id: "concrete-brutal",
    name: "Бетонный брутализм",
    description: "Серый бетон, нулевой радиус, тяжёлый каркас — архитектурная строгость",
    tags: ["брутализм", "бетон", "архитектура"],
    tokens: {
      radius: 0,
      borderWeight: 4,
      noise: 0.1,
      material: "concrete",
      palette: { ...MATERIAL_PRESETS.concrete, primary: "#B45309" },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      catalogTitle: "Спецификация · ГОСТ",
      trendingQueries: ["Арматура", "Сетка", "Швеллер", "Песок"],
    },
  }),
  buildPreset({
    id: "ocean-breeze",
    name: "Морской бриз",
    description: "Светлый бирюзово-синий, свежий и чистый, карточки с рейтингами",
    tags: ["свежий", "B2C", "сетка"],
    tokens: {
      radius: 14,
      borderWeight: 1,
      noise: 0.01,
      material: "chrome",
      palette: {
        background: "#F0F9F9",
        foreground: "#0F2E2C",
        card: "#FFFFFF",
        primary: "#0F766E",
        secondary: "#D9F0EE",
        muted: "#D9F0EE",
        mutedForeground: "#5C8A86",
        border: "#C9E4E1",
      },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 333-77-77",
      address: "Москва, Судостроительная ул., 18",
      promoTag: "Акция",
      promoTitle: "Щебень гранитный 5-20 — 2 450 ₽/м³",
      promoSubtitle: "Отгрузка вагонами и самосвалами по всей Московской области",
      catalogTitle: "Популярные товары",
      trendingQueries: ["Щебень", "Гравий", "Песок", "Отсев", "Керамзит"],
    },
  }),
  buildPreset({
    id: "vintage-industrial",
    name: "Винтажный индустриал",
    description: "Тёплый тёмный стиль с медным акцентом, ретро-типографика",
    tags: ["винтаж", "медь", "таблица"],
    tokens: {
      radius: 2,
      borderWeight: 2,
      noise: 0.09,
      material: "anthracite",
      palette: {
        background: "#17120E",
        foreground: "#F4F0EC",
        card: "#201A14",
        primary: "#D97B3D",
        secondary: "#2A221A",
        muted: "#2A221A",
        mutedForeground: "#A08A72",
        border: "#3A2F24",
      },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      phone: "+7 495 444-19-19",
      address: "Москва, Кожевническая ул., 7",
      catalogTitle: "Прайс-лист · Металлобаза",
      trendingQueries: ["Арматура", "Уголок", "Полоса", "Труба", "Лист"],
    },
  }),
  buildPreset({
    id: "lime-sport",
    name: "Лаймовый спорт",
    description: "Энергичный тёмный стиль с лаймовым акцентом, динамичная сетка",
    tags: ["энергия", "лайм", "сетка"],
    tokens: {
      radius: 6,
      borderWeight: 2,
      noise: 0.05,
      material: "anthracite",
      palette: {
        background: "#1A2416",
        foreground: "#F6FAF0",
        card: "#222E1B",
        primary: "#65A30D",
        secondary: "#2C3B22",
        muted: "#2C3B22",
        mutedForeground: "#93A87E",
        border: "#3A4C2E",
      },
      viewMode: "grid",
      heroMode: "split",
      searchMode: "marketplace",
    },
    content: {
      catalogTitle: "Каталог · быстрый заказ",
      trendingQueries: ["Арматура", "Профнастил", "Сетка", "Песок"],
    },
  }),
  buildPreset({
    id: "bordeaux",
    name: "Благородный бордо",
    description: "Тёмное вино с малиновым акцентом, премиальная сетка",
    tags: ["премиум", "бордо", "сетка"],
    tokens: {
      radius: 8,
      borderWeight: 1,
      noise: 0.04,
      material: "anthracite",
      palette: {
        background: "#171014",
        foreground: "#F4EEF1",
        card: "#211820",
        primary: "#D6437A",
        secondary: "#2E222A",
        muted: "#2E222A",
        mutedForeground: "#A98A97",
        border: "#3E2C36",
      },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 666-30-30",
      address: "Москва, Ленинградский пр-т, 37",
      promoTag: "Коллекция",
      promoTitle: "Нержавеющий прокат",
      promoSubtitle: "Трубы, листы, круги — с паспортами качества",
      catalogTitle: "Каталог · премиум",
      trendingQueries: ["Нержавейка", "Арматура", "Труба", "Лист"],
    },
  }),
  buildPreset({
    id: "royal-purple",
    name: "Королевский пурпур",
    description: "Глубокий фиолетовый с неоново-фиолетовым акцентом, маркетплейс",
    tags: ["пурпур", "маркетплейс", "сетка"],
    tokens: {
      radius: 10,
      borderWeight: 1,
      noise: 0.03,
      material: "anthracite",
      palette: {
        background: "#14101F",
        foreground: "#F1EEF8",
        card: "#1D1730",
        primary: "#8B5CF6",
        secondary: "#2A2140",
        muted: "#2A2140",
        mutedForeground: "#9C8FC0",
        border: "#3A2F57",
      },
      viewMode: "grid",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 888-50-50",
      address: "Москва, Алтуфьевское ш., 44",
      promoTag: "Новинка",
      promoTitle: "Композитная арматура",
      promoSubtitle: "Лёгкая, коррозионностойкая, от 30 ₽/м",
      catalogTitle: "Маркетплейс стройматериалов",
      trendingQueries: ["Композит", "Арматура", "Сетка", "Песок"],
    },
  }),
  buildPreset({
    id: "paper-mono",
    name: "Бумажный монохром",
    description: "Типографский стиль: белая бумага, чёрный текст, строгие линии",
    tags: ["типографика", "монохром", "редакция"],
    tokens: {
      radius: 2,
      borderWeight: 2,
      noise: 0.02,
      material: "chrome",
      palette: {
        background: "#FAFAFA",
        foreground: "#1F1F1F",
        card: "#FFFFFF",
        primary: "#1F1F1F",
        secondary: "#EDEDED",
        muted: "#EDEDED",
        mutedForeground: "#6B6B6B",
        border: "#D4D4D4",
      },
      viewMode: "table",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      catalogTitle: "Каталог · №1",
      trendingQueries: ["Арматура", "Труба", "Лист", "Песок"],
    },
  }),
  buildPreset({
    id: "emerald-forest",
    name: "Изумрудный лес",
    description: "Тёмно-зелёный с изумрудным акцентом, природная свежесть",
    tags: ["природа", "изумруд", "сетка"],
    tokens: {
      radius: 6,
      borderWeight: 1,
      noise: 0.05,
      material: "anthracite",
      palette: {
        background: "#0C1712",
        foreground: "#EEF5F1",
        card: "#13211A",
        primary: "#2FBF71",
        secondary: "#1C2F25",
        muted: "#1C2F25",
        mutedForeground: "#7FA893",
        border: "#27402F",
      },
      viewMode: "grid",
      heroMode: "split",
      searchMode: "compact",
    },
    content: {
      phone: "+7 495 111-60-60",
      address: "Москва, Волгоградский пр-т, 32",
      catalogTitle: "Каталог · эко",
      trendingQueries: ["Песок", "Щебень", "Гравий", "Арматура"],
    },
  }),
  buildPreset({
    id: "sunset-quarry",
    name: "Закат над карьером",
    description: "Тёплый тёмный стиль с янтарно-оранжевым акцентом, промо-слайдер",
    tags: ["закат", "тёплый", "промо"],
    tokens: {
      radius: 4,
      borderWeight: 2,
      noise: 0.07,
      material: "anthracite",
      palette: {
        background: "#17110C",
        foreground: "#F5F0EC",
        card: "#211A12",
        primary: "#F97316",
        secondary: "#2E2418",
        muted: "#2E2418",
        mutedForeground: "#A68F74",
        border: "#40331F",
      },
      viewMode: "table",
      heroMode: "promos",
      searchMode: "marketplace",
    },
    content: {
      phone: "+7 495 909-70-70",
      address: "Москва, Проектируемый пр-д, 12",
      promoTag: "Закат",
      promoTitle: "Песок и щебень — скидка 10% на самовывоз",
      promoSubtitle: "Карьеры Московской области: Домодедово, Воскресенск, Люберцы",
      catalogTitle: "Прайс · карьер",
      trendingQueries: ["Песок", "Щебень", "Отсев", "ПГС", "Гравий"],
    },
  }),
];

/** Найти предтему по id */
export function getStrikerPreset(id: string): ThemeConfigBlueprint | undefined {
  return STRIKER_PRESETS.find((p) => p.id === id);
}
